### ISSUE TITLE
Use of other custom ObjectMappers broken by gross reflection hack

### ISSUE THREAD

**Issue by dualspiral** [Sponge-RPG-dev/ConfigurateButWithBlackjackAndHookers#1]
https://github.com/Sponge-RPG-dev/ConfigurateButWithBlackjackAndHookers/blob/39d5fc8afdec5dab761b1edab14c4db33c2f1a98/src/main/java/cz/neumimto/config/blackjack/and/hookers/NotSoStupidObjectMapper.java#L41-L58

This is completely unnecssary and prevents other users from using their own object mapper without having to resort to their own hacks/workarounds. For example, you are breaking Nucleus. [**You should not be forcing people to use your object mapper like you do here.**](https://github.com/Sponge-RPG-dev/ConfigurateButWithBlackjackAndHookers/blob/39d5fc8afdec5dab761b1edab14c4db33c2f1a98/src/main/java/cz/neumimto/config/blackjack/and/hookers/ClassTypeNodeSerializer.java#L19)

Rather than ripping out a specific serialiser, you should:

* Remove the entire static block linked to above
* Create a child `TypeSerializerCollection` - `TypeSerializers.getDefaultSerializers().newChild()`
* Add your custom serialiser to that (child serialisers have higher priority than their parents)
* Use this child serialiser collection when creating a loader (via the [`ConfigurationOptions#withSerializers` in 3.7](https://configurate.aoeu.xyz/3.7/apidocs/ninja/leaping/configurate/ConfigurationOptions.html#withSerializers(ninja.leaping.configurate.objectmapping.serialize.TypeSerializerCollection)), `setSerializers` prior to that). While you're there, you should create an `ObjectMapperFactory` for your object mapper and set it in those options too.

That way, the projects that want to use your extensions can, while those that don't aren't forced to anyway. I get that you might see this as completely compatible with the standard object mapper - that's fine, but it's not compatible with my object mapper. Please stop forcing people to use your mapper when this project is being used.

**Comment by NeumimTo** [comment]
@dualspiral thanks for reporting,  im aware of this but i no longer need this library in my projects so i cannot say when or if this gets ever fixed.  
Tbh best option would be to put these features to configurate 

It was a fast hack to make it work as i wanted.

Eventually i discovered that former version of configurate lacks too much features i was hoping for,  so i switched to nightconfig.
